#!/usr/bin/env php
<?php

$autoload = __DIR__.'/vendor/autoload.php';
if(!file_exists($autoload)){
    $autoload = __DIR__.'/../../autoload.php';
}
require $autoload;


class Dispatcher implements \Illuminate\Contracts\Events\Dispatcher
{
    public function listen($events, $listener){}
    public function hasListeners($eventName){}
    public function subscribe($subscriber){}
    public function until($event, $payload = []){}
    public function dispatch($event, $payload = [], $halt = false){}
    public function push($event, $payload = []){}
    public function flush($event){}
    public function forget($event){}
    public function forgetPushed(){}
    public function fire(){}
}

$env = new \Symfony\Component\Dotenv\Dotenv();

$container   = \Illuminate\Container\Container::getInstance();
$dispatcher  = new Dispatcher();
$application = new \Illuminate\Console\Application($container, $dispatcher, '0.0.3');

$application->add(new \lanzhi\ddd\installer\InitCommand());
$application->add(new \lanzhi\ddd\installer\ClearCommand());

try{
    class_exists('Illuminate\Console\Events\CommandFinished');//不能省略
    $status = $application->run();
    exit($status);
}catch (Throwable $exception){
    echo sprintf("%s: %s in %s:%s\n", get_class($exception), $exception->getMessage(), $exception->getFile(), $exception->getLine());
    echo "Stack trace:\n";
    echo $exception->getTraceAsString(),"\n";
}
